### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating 'shortcutMethod.bind(null, addMethods)')

### ISSUE THREAD

**Issue by mdix** [stampit-org/stampit#175] opened 2015-10-09 12:23 UTC
I tried to use stampit with karma & gulp, but I'm always getting the above mentioned error. I created a branch with my current setup [here](https://github.com/mdix/es6-babel-browserify-karma-boilerplate/tree/adding-stampit).

Whoever wants to help, just check it out, switch to the branch 

```
git checkout adding-stampit
npm install
./node_modules/.bin/gulp
```

and you should be able to see the error message.

Would appreciate help on this. Thanks in advance.

**Comment by koresar** [comment] 2015-10-09 20:26
Hello.

1. I'm pretty sure it's not stampit related error. Could you show full error? With the stack trace.
1. In [this file](https://github.com/mdix/es6-babel-browserify-karma-boilerplate/blob/adding-stampit/src/stamp/Stamp.js) you are exporting not a stamp but an object. Maybe export stamp to match the file name?
1. In your test the `expect(myStamp.sayHello()).toEqual('Hello');` line might fail. I don't see an assetion module in the karma conf, or package.json, or gulpfile.
1. You put stampit as a devDependency for some reason. Although, you are importing it in `src/`.

I believe, questions like this should be asked at Stackoverflow. :) I'd be gald to answer them there.

Cheers!

**Comment by mdix** [comment] 2015-10-09 20:30
1.
```
[22:28:04] Starting Karma server...
INFO [framework.browserify]: bundle built
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket 6izvHPLccA5QZymyShp2 with id 70500136
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: 'undefined' is not a function (evaluating 'shortcutMethod.bind(null, addMethods)')
  at /var/folders/jf/00gb7hd17yl853ww6sw44pqh5r01xc/T/b6ed61688795a1cd4f8fe9f953283a1b.browserify:369



/Users/marc.dix/projects/setups/babel_karma_gulp/gulpfile.js:38
            throw err;
            ^
Error: karma exited with code 1
    at done (/Users/marc.dix/projects/setups/babel_karma_gulp/node_modules/gulp-karma/index.js:56:30)
    at ChildProcess.<anonymous> (/Users/marc.dix/projects/setups/babel_karma_gulp/node_modules/gulp-karma/index.js:82:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

2. I already did that. Same error.

3. Same line works when asserting in the spec where I used ES6 `class`. Even if it would fail, it would be a different error.

4. Yeah, I accidentally added everything as devDependency. Will change that. Thanks.

Best
Marc

**Comment by ericelliott** [comment] 2015-10-09 20:34
Why are you rethrowing the error from Karma? Doesn't that just obscure the stack trace and the real source of the error?

**Comment by mdix** [comment] 2015-10-09 20:36
@ericelliott Not really, running directly with karma (& log level to DEBUG):

```
...
DEBUG [web-server]: serving (cached): /Users/marc.dix/projects/setups/babel_karma_gulp/node_modules/karma-jasmine/lib/adapter.js
DEBUG [web-server]: serving (cached): /Users/marc.dix/projects/setups/babel_karma_gulp/spec/stamp/StampSpec.js
DEBUG [phantomjs.launcher]: Hello

PhantomJS 1.9.8 (Mac OS X 0.0.0) LOG: 'Hello'

PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: 'undefined' is not a function (evaluating 'shortcutMethod.bind(null, addMethods)')
  at /var/folders/jf/00gb7hd17yl853ww6sw44pqh5r01xc/T/b452d365a5cb034f23637b1beaf0a743.browserify:369


DEBUG [karma]: Run complete, exiting.
DEBUG [launcher]: Disconnecting all browsers
DEBUG [framework.browserify]: cleaning up
DEBUG [launcher]: Process PhantomJS exited with code 0
DEBUG [temp-dir]: Cleaning temp dir /var/folders/jf/00gb7hd17yl853ww6sw44pqh5r01xc/T/karma-90092623
...
```

**Comment by koresar** [comment] 2015-10-09 20:42
Something is wrong with the build system. `gulp build` fails exactly the same way.

**Comment by mdix** [comment] 2015-10-09 20:43
```
gulp.task('default', ['build']);
```
might be the reason for that. Running `gulp` is the same as `gulp build` because of the line above.

**Comment by ericelliott** [comment] 2015-10-09 20:45
@mdix have you tried bypassing the build completely?

**Comment by mdix** [comment] 2015-10-09 20:47
@ericelliott Yes, I did. Mind reading [this](https://github.com/stampit-org/stampit/issues/175#issuecomment-146980360) again?

**Comment by koresar** [comment] 2015-10-09 20:52
Is the build system config runs browserify twice? Browserifying a vrowserified code?

**Comment by mdix** [comment] 2015-10-09 20:56
@koresar No. The build system is only running all the stuff once to build (`build.js`). The whole stuff runs again when karma is executed. But both work with fresh source files, so we're not browserifying browserified code here.

**Comment by ericelliott** [comment] 2015-10-09 20:57
@mdix Ah, I meant the whole system, including karma. I.e., just run the JS files and `console.log()` the results.

**Comment by koresar** [comment] 2015-10-09 20:58
Is there a reason to not run the tests against the just built `build.js`?

**Comment by mdix** [comment] 2015-10-09 21:01
@ericelliott Just an attempt to save me some work: Would your question be answered with "If I run `build.js`, it logs out 'Hello' twice and no error is shown."? If this doesn't answer your question, I have to somehow browserify and babelify the source file on the console. Never did that, as we have nice build tools in 2015. So?

**Comment by mdix** [comment] 2015-10-09 21:05
@koresar I'm unittesting, so I'm not interesting in how the components work together, means I'm not interested in what app.js does at all and I don't want to get problems with whatever sideffects might occur when implicitly running `app.js` (as it's part of `build.js`). We drift off a bit, don't we?

**Comment by koresar** [comment] 2015-10-09 21:09
In my opinion the build system is broken. Stampit was tested by thousands of different setups and environments. Have never had an issue.

**Comment by koresar** [comment] 2015-10-09 21:15
Taking the logs above, @mdix, could you show us this file?
`/var/folders/jf/00gb7hd17yl853ww6sw44pqh5r01xc/T/b452d365a5cb034f23637b1beaf0a743.browserify`
Thanks

**Comment by mdix** [comment] 2015-10-09 21:16
@koresar Well, at least I can try. Please wait a few seconds, I gotta check how to keep the temp file created by karam.

**Comment by koresar** [comment] 2015-10-09 21:18
Also, I believe this can be an issue of build babelifying. Stampit is wirtten in ES6, but the `main:` file is an ES5 babel generated output. Running babel twice on the same file might be causing issues.

**Comment by koresar** [comment] 2015-10-09 21:18
Also, I believe this can be an issue of build babelifying. Stampit is wirtten in ES6, but the `main:` file is an ES5 babel generated output. Running babel twice on the same file might be causing issues.

**Comment by mdix** [comment] 2015-10-09 21:28
@koresar I'm sorry, but I'm not able to quickly find a way how to keep the browserify temp file. Other suggestions? (Still trying to figure it out)

**Comment by koresar** [comment] 2015-10-09 21:32
All we need is the build result of this part:
```json

        preprocessors: {
            'src/**/*.js': ['browserify'],
            'spec/**/*.js': ['browserify']
        },

        browserify: {
            transform: ['babelify']
        },
```

You can try running the appropriate set of commands manually.

P.S.
One of the reasons I don't like grunt/gulp/karma/etc is because of this bloody maaagic happening behind the scenes.

**Comment by mdix** [comment] 2015-10-09 21:37
@koresar Yea, and I'd love to provide you with the output of this. Seems there's no configuration option in browserify to keep the temp file.

Concerning the build tools: Thanks for your opinion on this, but you know that discussions on that tend to get pretty long (and I just want to get my problem solved).

**Comment by ericelliott** [comment] 2015-10-09 21:37
Delete all the stamp stuff. Does it still fail?

**Comment by mdix** [comment] 2015-10-09 21:38
@ericelliott No. Works fine without stamp.

**Comment by koresar** [comment] 2015-10-09 21:39
I found the way to keep the temp files.
Commend out the `rimraf` at the bottom:
`node_modules/karma/lib/temp_dir.js`

**Comment by mdix** [comment] 2015-10-09 21:42
@koresar Thanks, unfortunately it's not working. Are you sure that karma is creating the file?

**Comment by koresar** [comment] 2015-10-09 21:47
Yes. I'm browsing it now. :) (Looks legit though.)
0) In karma.conf.js replace `LOG_INFO` with `LOG_DEBUG`.
1) Comment out the `rimraf` line.
2) Run `gulp`. The karma should run but not quit.
3) Take a look at the only file in this folder. It should look like this in the output:
`DEBUG [temp-dir]: Cleaning temp dir /var/folders/zy/c7yfqxq11qz3715xx20h_rrm0000gn/T/karma-70559475`
4) There will be URL. Open it in a browser. Open dev tools -> source. Find there the generated file.

;)

**Comment by mdix** [comment] 2015-10-09 21:49
@koresar Ok, please stand by. Gotta give my baby some milk, hope to be back in 5 min.

**Comment by ericelliott** [comment] 2015-10-09 21:54
@mdix It isn't a problem in Stampit, and you can verify that for yourself. Pop open Node at the prompt, and type:

```js
var stampit = require('stampit');
var myStamp = stampit().methods({sayHello: function() { return 'Hello'; }});
myStamp().sayHello(); // Hello
```

I just copied and pasted the body of your Stamp code.

**Comment by koresar** [comment] 2015-10-09 21:55
Yes, Eric. It looks like a bug somewhere in PhantomJS, or Karma, or Babelify, or Browserify, or else.

**Comment by mdix** [comment] 2015-10-09 21:59
@ericelliott @koresar Thanks for helping me to identify the direction. Now it'll be a long road to finding the root cause. The funny thing is: I did not mention this, but earlier in this discussion I ran karma with `build.js` (and disabled all the transforms) and still had the same error. Based on this discovery I should probably check karma or phantom, as it proofs that the *ifys are working fine.

**Comment by ericelliott** [comment] 2015-10-09 21:59
I'm just gonna leave this here...

[Why I use Tape instead of karma and so should you ;)](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4)

**Comment by mdix** [comment] 2015-10-09 22:01
@ericelliott I read it. Mulitple times. I also read the comment from the mocha guy. IMO most of your points are wrong. (But please don't get me wrong, I really ~~like~~ adore you & your writings on medium - but tape is something I'll definitely not use in production).

**Comment by mdix** [comment] 2015-10-09 22:05
I think the next step is to replace `gulp-karma` with `karma`, because the development of the `gulp-karma` wrapper has been stopped a long time ago. Let's see if this fixes the problem.

**Comment by ericelliott** [comment] 2015-10-09 22:08
> IMO most of your points are wrong.

I'm looking forward to reading your rebuttal post. =)

**Comment by koresar** [comment] 2015-10-10 00:06
I'm closing this issue as not related to stampit.
@mdix Feel free to create a new one after you find the cause of the problem is actually stampit.

Cheers

**Closed** 2015-10-10 00:22 UTC

**Comment by mdix** [comment] 2015-10-10 11:43
@ericelliott @koresar Just in case you're interested: Looks like it's a [phantomjs](https://github.com/ariya/phantomjs) (or [karma-phantomjs-launcher](https://github.com/karma-runner/karma-phantomjs-launcher)) issue. It works fine with Chrome (using the [karma-chrome-launcher](https://github.com/karma-runner/karma-chrome-launcher). Big thanks to both of you for helping me to identify the cause.

**Comment by koresar** [comment] 2015-10-11 01:25
@mdix Thanks for the followup. I really appreciate that.

As usual, any further questions are welcome.

**Comment by tcrosen** [comment] 2015-10-19 14:12
The problem is PhantomJS is missing `Function.bind`.  
Include the [polyfill](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind#Polyfill) and it will work.

**Comment by koresar** [comment] 2015-10-19 22:22
Oh. Thanks Terry!
