### ISSUE TITLE
npm install failing on eslint

### ISSUE THREAD

**Issue by davewallace** [stampit-org/stampit#265] opened 2016-10-18 11:47 UTC
Hi, sorry to plague you, bought Eric's book & read the docs, I totally get what you're up to with stampit - but man, tools just layering barrier upon barrier for me. Can't get your hard work up & running.

Failing both a `npm install` and `yarn`, on eslint check, error source from install doesn't point to much: https://gist.github.com/davewallace/ac4db8ce29629f33f7cbc0cedfd1818d

When I manually run `eslint src` (after having to install eslint globally) I get a more honed error: https://gist.github.com/davewallace/73a35489e79cf0674c7f75f02dafe8a3

Step-by-step fixes absolutely most welcome or otherwise links & advice for a 0.6 level JS dev who doesn't live & breathe dependency handling. Likely a PITA for you... but I can't even toy with your most excellent concepts at this point :/

**Comment by FredyC** [comment] 2016-10-18 12:22
So let me get clear. You just run `npm install stampit` and this is the error you got? What is your version of Node/NPM, please?

**Comment by koresar** [comment] 2016-10-18 14:23
Node 4,  npm 2. In the first gist. 

Seems like Dave ran "npm test" inside the stampit. Which is wrong from user's perspective. But correct from the stampit developer point. 
Tell me, why you are running test and eslint inside stampit? Are you gonna help us develop it?

**Comment by koresar** [comment] 2016-10-19 05:46
Hello again @davewallace 

I'll close this issue for now as not a bug.

Feel free to reopen if you think stampit can be improved in this regards. Also, this issue is open for discussions regardless of the closed status.

Cheers :)

**Closed by koresar** 2016-10-19 05:46 UTC

**Comment by davewallace** [comment] 2016-10-20 09:33
Hi folks, sorry didn't get a chance to reply a bit quicker.

@koresar My gist omitted the actual command I ran, I was running `npm install` and then tried `yarn`, not actually `npm test`. The test was something I presume was part of the install process. I'd love to pitch in and help, I'm probably not quite at your level though - I just felt the whole idea of stamps was a really good one, and wanted to give them a test run.

@FredyC Unfortunately installing eslint globally has been the only way I've been able to successfully get it working for a couple of prototyping efforts with React, and now Stampit. I know it's not ideal. I hear it's possible to refer the binaries directly inside node_modules, post install, and though outside the scope of this issue maybe I'd appreciate any solid leads for local installation of eslint when using an IDE like SublimeText 3on Windows 10.

**Comment by koresar** [comment] 2016-10-20 09:57
Looks like your eslint issue was a yarn bug. Not sure though.

Currently, I'm thinking of improving the infected stamps a bit. I feel the need for more.

But looks like you'r doing great atm. :) Have fun!

**Comment by davewallace** [comment] 2016-10-20 10:10
Great, if you don't mind sharing, what did you have in mind for the infected stamps?

When I looked at stamps first and saw the "last wins" approach to functional composition, my first reaction was to think of optional controlled queueing, but really that seems very brittle & likely over-complicating things.

**Comment by koresar** [comment] 2016-10-20 12:33
@davewallace here is the proposal. https://github.com/stampit-org/stamp-specification/issues/109
